// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import googleiot "github.com/kml183/room-environment-monitor/internal/google-iot"
import mock "github.com/stretchr/testify/mock"
import sensors "github.com/kml183/room-environment-monitor/internal/sensors"

// GoogleIOTService is an autogenerated mock type for the GoogleIOTService type
type GoogleIOTService struct {
	mock.Mock
}

// PublishDeviceState provides a mock function with given fields: ctx, status
func (_m *GoogleIOTService) PublishDeviceState(ctx context.Context, status *googleiot.DeviceStatus) error {
	ret := _m.Called(ctx, status)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *googleiot.DeviceStatus) error); ok {
		r0 = rf(ctx, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PublishSensorData provides a mock function with given fields: ctx, data
func (_m *GoogleIOTService) PublishSensorData(ctx context.Context, data *sensors.SensorData) error {
	ret := _m.Called(ctx, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sensors.SensorData) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SubsribeToConfigChanges provides a mock function with given fields: ctx
func (_m *GoogleIOTService) SubsribeToConfigChanges(ctx context.Context) (*googleiot.ConfigMessage, error) {
	ret := _m.Called(ctx)

	var r0 *googleiot.ConfigMessage
	if rf, ok := ret.Get(0).(func(context.Context) *googleiot.ConfigMessage); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*googleiot.ConfigMessage)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
