// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// HttpServerService is an autogenerated mock type for the HttpServerService type
type HttpServerService struct {
	mock.Mock
}

// Start provides a mock function with given fields: ip
func (_m *HttpServerService) Start(ip string) error {
	ret := _m.Called(ip)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(ip)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
