// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"

import mock "github.com/stretchr/testify/mock"

// IOTServerService is an autogenerated mock type for the IOTServerService type
type IOTServerService struct {
	mock.Mock
}

// PublishDeviceStatus provides a mock function with given fields: _a0
func (_m *IOTServerService) PublishDeviceStatus(_a0 context.Context) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PublishSensorDataSnapshot provides a mock function with given fields: _a0
func (_m *IOTServerService) PublishSensorDataSnapshot(_a0 context.Context) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PublishSensorDataSnapshotHandler provides a mock function with given fields: _a0
func (_m *IOTServerService) PublishSensorDataSnapshotHandler(_a0 context.Context) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SubscribeToIOTCoreConfig provides a mock function with given fields: _a0
func (_m *IOTServerService) SubscribeToIOTCoreConfig(_a0 context.Context) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
