FROM ubuntu:24.04

# Make sure the
RUN mkdir -p /usr/src/rem-iot
COPY .justfile /usr/src/rem-iot
WORKDIR /usr/src/rem-iot

# Install System Packages
RUN apt-get update && \
    apt-get install -y \
    python3 \
    python3-pip \
    python3-dev \
    clang \
    clang-format \
    curl \
    tree \
    just

# Install all of the needed dependencies to build the rem-iot
RUN just bootstrap

