// Code generated by mockery v1.0.0. DO NOT EDIT.

package googleiot

import context "context"
import mock "github.com/stretchr/testify/mock"
import sensors "room-environment-monitor-client/internal/sensors"

// MockInterface is an autogenerated mock type for the Interface type
type MockInterface struct {
	mock.Mock
}

// PublishSensorData provides a mock function with given fields: ctx, data
func (_m *MockInterface) PublishSensorData(ctx context.Context, data *sensors.SensorData) error {
	ret := _m.Called(ctx, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sensors.SensorData) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SubsribeToConfigChanges provides a mock function with given fields: ctx
func (_m *MockInterface) SubsribeToConfigChanges(ctx context.Context) (*ConfigMessage, error) {
	ret := _m.Called(ctx)

	var r0 *ConfigMessage
	if rf, ok := ret.Get(0).(func(context.Context) *ConfigMessage); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ConfigMessage)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
